export interface Skills {
  heading: number,
  crossing: number,
  corner: number,
  tackling: number,
  finishing: number,
  dribbling: number,
  free_kick: number,
  marking: number,
  penalty: number,
  passing: number,
  first_touch: number,
  technique: number,
  discipline: number,
  aggression: number,
  anticipation: number,
  concentration: number,
  decision: number,
  determination: number,
  leadership: number,
  positioning: number,
  teamwork: number,
  vision: number | null,
  acceleration: number,
  agility: number,
  strength: number,
  jumping_reach: number,
  stamina: number,
  pace: number,
}

export const Skill: Skills = {
  heading: 10,
  crossing: 8,
  corner: 15,
  tackling: 20,
  finishing: 12,
  dribbling: 2,
  free_kick: 20,
  marking: 17,
  penalty: 0,
  passing: 14,
  first_touch: 4,
  technique: 0,
  aggression: 19,
  anticipation: 9,
  concentration: 11,
  decision: 13,
  determination: 7,
  discipline: 17,
  leadership: 11,
  positioning: 3,
  teamwork: 20,
  vision: 0,
  acceleration: 16,
  agility: 15,
  jumping_reach: 6,
  pace: 12,
  stamina: 19,
  strength: 9,
}
